### ISSUE TITLE
.well-known endpoint resolution

### ISSUE THREAD

**Issue by panva** [oauth-wg/draft-ietf-oauth-resource-metadata#17]
The draft [currently](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-resource-metadata-01#section-3) (and the examples in it) follow this language

> Protected resources supporting metadata MUST make a JSON document containing metadata as specified in [Section 2](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-resource-metadata-01#PRMetadata) available at a path formed by concatenating a well-known URI string such as /.well-known/oauth-protected-resource to the protected resource's resource identifier.

This means (taken from an example in the draft):

```
    GET /resource1/.well-known/oauth-protected-resource HTTP/1.1
    Host: resource.example.com
```

This is inconsistent with RFC8414 (and its normative dependencies) which says

> If the issuer identifier value contains a path component, any terminating "/" MUST be removed before inserting "/.well-known/" and the well-known URI suffix between the host component and the path component.

This means (taken from an example in RFC8414):

```
     GET /.well-known/oauth-authorization-server/issuer1 HTTP/1.1
     Host: example.com
```

The RFC8414 way kind of hampers the ability to host these documents in multi-tenant system on certain deployments but i'm unsure if we can justify not doing it this way.

**Comment by bc-pi** [comment]
Thanks @panva, this was the subject of my comments in [the meeting today](https://notes.ietf.org/notes-ietf-118-oauth#Protected-Resource-Metadata-%E2%80%93-Mike-Jones-Aaron-Parecki-20-min). I do think that the way it's done in the draft currently makes sense for the context and is preferable.  But it might raise some objections in IESG etc. review. I don't honestly know what the best course of action is. But wanted to bring it up earlier rather than later. Perhaps Roman's suggestion of asking the HTTP directorate for an early review in hope of avoiding surprise down the line?

**Comment by bc-pi** [comment]
The draft does say the following [here](https://www.ietf.org/archive/id/draft-ietf-oauth-resource-metadata-01.html#section-3.1-6), which maybe provides sufficient justification. Maybe.

> Using path components enables supporting multiple resources per host. This is required in some multi-tenant hosting configurations. This use of .well-known is for supporting multiple resources per host; unlike its use in [[RFC5785](https://www.ietf.org/archive/id/draft-ietf-oauth-resource-metadata-01.html#RFC5785)], it does not provide general information about the host.
