### ISSUE TITLE
Question: What should the WWW-Authenticate header return

### ISSUE THREAD

**Issue by aaronpk** [oauth-wg/draft-ietf-oauth-resource-metadata#8]
Should the header return the full path to the Resource Metadata document, or return the resource identifier?

* RS Metadata document: the client fetches the exact URL returned
* Resource Identifier: the client builds the metadata URL by appending .well-known... and then fetches the URL

What are the implications of this for resources that differ by path? (see mailing list thread about path-based resources that require different scopes)

**Comment by selfissued** [comment]
I'm increasingly of the view that the resource identifier should be returned, which is what the draft already does.  This aligns with the `resource` value in https://www.rfc-editor.org/rfc/rfc8707.html , which we normatively use.

I propose that we say that during IETF 118 in Prague.  If we get consensus on this, it will close our last remaining issue.

**Comment by randomstuff** [comment]
> I'm increasingly of the view that the resource identifier should be returned, which is what the draft already does. This aligns with the resource value in https://www.rfc-editor.org/rfc/rfc8707.html , which we normatively use.

I'm wondering why the [related PR](https://github.com/oauth-wg/draft-ietf-oauth-resource-metadata/pull/20) ended up the other route (advertising the URI of the resource metadata instead).

Advertising the resource identifier in the `WWW-Authenticate` would be more consistent with existing OAuth specifications as you pointed out.

Advertising the resource identifier in the `WWW-Authenticate` would make it possible for the client application to fetch an application-specific metadata documents (`/.well-known/myapplication-protected-resource/foo`) if it can handle it and the generic one (`/.well-known/oauth-protected-resource/foo`) otherwise.

**Comment by aaronpk** [comment]
See the minutes from IETF 118 in November 2023 for where this was discussed in the working group: https://datatracker.ietf.org/doc/minutes-118-oauth-202311101200/#protected-resource-metadata--mike-jones-aaron-parecki-20-min
